minimum_pre_commit_version: "3.7.0"
default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path Cargo.toml --
        language: system
        files: \.rs$
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path Cargo.toml --all-targets --all-features -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
