import numpy as np
import numpy.typing as npt

def delaunay(points: npt.NDArray[np.float64]) -> npt.NDArray[np.int32]: ...
def convex_hull(points: npt.NDArray[np.float64]) -> npt.NDArray[np.int32]: ...
